// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html


// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::init_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::init_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::_get_id_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::_get_id_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::loadFiles_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::loadFiles_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::_get_loadFilesHint_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::_get_loadFilesHint_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::shutdown_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::shutdown_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::close_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::close_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::axisar_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::axisar_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::b1900_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::b1900_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::b1950_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::b1950_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::bodc2n_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::bodc2n_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::boddef_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::boddef_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::bodfnd_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::bodfnd_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::bodn2c_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::bodn2c_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::bodvar_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::bodvar_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::cgv2el_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::cgv2el_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::chkin_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::chkin_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::chkout_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::chkout_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::cidfrm_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::cidfrm_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::ckgp_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::ckgp_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::ckgpav_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::ckgpav_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::clight_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::clight_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::cnmfrm_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::cnmfrm_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::conics_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::conics_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::convrt_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::convrt_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::cyllat_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::cyllat_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::cylrec_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::cylrec_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::cylsph_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::cylsph_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::det_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::det_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::dpmax_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::dpmax_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::dpmin_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::dpmin_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::dpr_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::dpr_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::dtpool_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::dtpool_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::dvdot_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::dvdot_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::dvhat_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::dvhat_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::edlimb_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::edlimb_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::ekfind_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::ekfind_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::ekgc_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::ekgc_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::ekgd_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::ekgd_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::ekgi_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::ekgi_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::eknelt_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::eknelt_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::ekpsel_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::ekpsel_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::el2cgv_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::el2cgv_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::et2utc_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::et2utc_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::etcal_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::etcal_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::eul2m_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::eul2m_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::eul2xf_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::eul2xf_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::expool_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::expool_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::frame_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::frame_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::frinfo_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::frinfo_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::frmnam_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::frmnam_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::gcpool_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::gcpool_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::gdpool_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::gdpool_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::georec_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::georec_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::getfov_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::getfov_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::gipool_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::gipool_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::gnpool_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::gnpool_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::halfpi_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::halfpi_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::ident_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::ident_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::illum_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::illum_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::inedpl_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::inedpl_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::inelpl_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::inelpl_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::inrypl_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::inrypl_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::intmax_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::intmax_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::intmin_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::intmin_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::invert_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::invert_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::isrot_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::isrot_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::j1900_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::j1900_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::j1950_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::j1950_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::j2000_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::j2000_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::j2100_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::j2100_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::jyear_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::jyear_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::kdata_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::kdata_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::ktotal_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::ktotal_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::latcyl_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::latcyl_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::latrec_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::latrec_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::latsph_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::latsph_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::ltime_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::ltime_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::m2eul_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::m2eul_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::m2q_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::m2q_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::mequ_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::mequ_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::mtxm_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::mtxm_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::mtxv_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::mtxv_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::mxm_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::mxm_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::mxmt_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::mxmt_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::mxv_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::mxv_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::namfrm_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::namfrm_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::nearpt_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::nearpt_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::npedln_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::npedln_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::npelpt_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::npelpt_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::nplnpt_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::nplnpt_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::nvc2pl_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::nvc2pl_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::nvp2pl_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::nvp2pl_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::oscelt_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::oscelt_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::pcpool_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::pcpool_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::pdpool_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::pdpool_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::pi_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::pi_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::pipool_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::pipool_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::pjelpl_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::pjelpl_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::pl2nvc_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::pl2nvc_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::pl2nvp_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::pl2nvp_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::pl2psv_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::pl2psv_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::prop2b_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::prop2b_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::psv2pl_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::psv2pl_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::pxform_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::pxform_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::q2m_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::q2m_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::radrec_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::radrec_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::rav2xf_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::rav2xf_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::raxisa_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::raxisa_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::reccyl_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::reccyl_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::recgeo_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::recgeo_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::reclat_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::reclat_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::recrad_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::recrad_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::recsph_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::recsph_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::rotate_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::rotate_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::rotmat_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::rotmat_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::rotvec_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::rotvec_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::rpd_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::rpd_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::rquad_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::rquad_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::saelgv_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::saelgv_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::scdecd_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::scdecd_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::sce2c_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::sce2c_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::sce2s_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::sce2s_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::scencd_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::scencd_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::scfmt_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::scfmt_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::scpart_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::scpart_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::scs2e_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::scs2e_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::sct2e_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::sct2e_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::sctiks_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::sctiks_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::spd_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::spd_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::sphcyl_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::sphcyl_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::sphlat_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::sphlat_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::sphrec_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::sphrec_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::spkapo_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::spkapo_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::spkapp_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::spkapp_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::spkez_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::spkez_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::spkezp_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::spkezp_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::spkezr_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::spkezr_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::spkgeo_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::spkgeo_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::spkgps_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::spkgps_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::spkpos_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::spkpos_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::spkssb_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::spkssb_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::stelab_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::stelab_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::stpool_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::stpool_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::str2et_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::str2et_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::subpt_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::subpt_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::subsol_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::subsol_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::surfnm_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::surfnm_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::surfpt_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::surfpt_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::sxform_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::sxform_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::timdef_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::timdef_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::timout_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::timout_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::tipbod_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::tipbod_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::tisbod_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::tisbod_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::tkvrsn_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::tkvrsn_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::tparse_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::tparse_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::tpictr_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::tpictr_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::tsetyr_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::tsetyr_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::twopi_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::twopi_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::twovec_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::twovec_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::tyear_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::tyear_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::ucrss_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::ucrss_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::unitim_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::unitim_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::unorm_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::unorm_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::utc2et_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::utc2et_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vadd_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vadd_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vcrss_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vcrss_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vdist_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vdist_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vdot_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vdot_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vequ_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vequ_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vhat_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vhat_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vlcom3_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vlcom3_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vlcom_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vlcom_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vminus_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vminus_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vnorm_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vnorm_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vperp_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vperp_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vprjp_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vprjp_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vprjpi_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vprjpi_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vproj_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vproj_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vrel_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vrel_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vrotv_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vrotv_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vscl_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vscl_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vsep_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vsep_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vsub_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vsub_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vtmv_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vtmv_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::vzero_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::vzero_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::xf2eul_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::xf2eul_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::xf2rav_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::xf2rav_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::xpose6_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::xpose6_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

// TAO_IDL - Generated from
// be/be_interface.cpp:1915

ACE_INLINE
void
POA_jpl::mipl::spice::corba::MiplSpiceLib::xpose_skel (
    TAO_ServerRequest & server_request,
    void * servant_upcall,
    void * servant
    ACE_ENV_ARG_DECL
  )
{
  POA_jpl::mipl::spice::corba::SpiceLib * const impl = static_cast<POA_jpl::mipl::spice::corba::MiplSpiceLib *> (servant);
  POA_jpl::mipl::spice::corba::SpiceLib::xpose_skel (
      server_request,
      servant_upcall,
      impl
      ACE_ENV_ARG_PARAMETER
    );
}

