// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html


// TAO_IDL - Generated from
// be/be_visitor_array/array_ci.cpp:158

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::Vector3,
    jpl::mipl::spice::corba::Vector3_slice,
    jpl::mipl::spice::corba::Vector3_tag
  >::free (
    jpl::mipl::spice::corba::Vector3_slice * _tao_slice
  )
{
  jpl::mipl::spice::corba::Vector3_free (_tao_slice);
}

ACE_INLINE
jpl::mipl::spice::corba::Vector3_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::Vector3,
    jpl::mipl::spice::corba::Vector3_slice,
    jpl::mipl::spice::corba::Vector3_tag
  >::dup (
    const jpl::mipl::spice::corba::Vector3_slice * _tao_slice
  )
{
  return jpl::mipl::spice::corba::Vector3_dup (_tao_slice);
}

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::Vector3,
    jpl::mipl::spice::corba::Vector3_slice,
    jpl::mipl::spice::corba::Vector3_tag
  >::copy (
    jpl::mipl::spice::corba::Vector3_slice * _tao_to,
    const jpl::mipl::spice::corba::Vector3_slice * _tao_from
  )
{
  jpl::mipl::spice::corba::Vector3_copy (_tao_to, _tao_from);
}

ACE_INLINE
jpl::mipl::spice::corba::Vector3_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::Vector3,
    jpl::mipl::spice::corba::Vector3_slice,
    jpl::mipl::spice::corba::Vector3_tag
  >::alloc (void)
{
  return jpl::mipl::spice::corba::Vector3_alloc ();
}


// TAO_IDL - Generated from
// be/be_visitor_array/array_ci.cpp:158

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::Matrix33,
    jpl::mipl::spice::corba::Matrix33_slice,
    jpl::mipl::spice::corba::Matrix33_tag
  >::free (
    jpl::mipl::spice::corba::Matrix33_slice * _tao_slice
  )
{
  jpl::mipl::spice::corba::Matrix33_free (_tao_slice);
}

ACE_INLINE
jpl::mipl::spice::corba::Matrix33_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::Matrix33,
    jpl::mipl::spice::corba::Matrix33_slice,
    jpl::mipl::spice::corba::Matrix33_tag
  >::dup (
    const jpl::mipl::spice::corba::Matrix33_slice * _tao_slice
  )
{
  return jpl::mipl::spice::corba::Matrix33_dup (_tao_slice);
}

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::Matrix33,
    jpl::mipl::spice::corba::Matrix33_slice,
    jpl::mipl::spice::corba::Matrix33_tag
  >::copy (
    jpl::mipl::spice::corba::Matrix33_slice * _tao_to,
    const jpl::mipl::spice::corba::Matrix33_slice * _tao_from
  )
{
  jpl::mipl::spice::corba::Matrix33_copy (_tao_to, _tao_from);
}

ACE_INLINE
jpl::mipl::spice::corba::Matrix33_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::Matrix33,
    jpl::mipl::spice::corba::Matrix33_slice,
    jpl::mipl::spice::corba::Matrix33_tag
  >::alloc (void)
{
  return jpl::mipl::spice::corba::Matrix33_alloc ();
}


// TAO_IDL - Generated from
// be/be_visitor_array/array_ci.cpp:158

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::Quaternion,
    jpl::mipl::spice::corba::Quaternion_slice,
    jpl::mipl::spice::corba::Quaternion_tag
  >::free (
    jpl::mipl::spice::corba::Quaternion_slice * _tao_slice
  )
{
  jpl::mipl::spice::corba::Quaternion_free (_tao_slice);
}

ACE_INLINE
jpl::mipl::spice::corba::Quaternion_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::Quaternion,
    jpl::mipl::spice::corba::Quaternion_slice,
    jpl::mipl::spice::corba::Quaternion_tag
  >::dup (
    const jpl::mipl::spice::corba::Quaternion_slice * _tao_slice
  )
{
  return jpl::mipl::spice::corba::Quaternion_dup (_tao_slice);
}

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::Quaternion,
    jpl::mipl::spice::corba::Quaternion_slice,
    jpl::mipl::spice::corba::Quaternion_tag
  >::copy (
    jpl::mipl::spice::corba::Quaternion_slice * _tao_to,
    const jpl::mipl::spice::corba::Quaternion_slice * _tao_from
  )
{
  jpl::mipl::spice::corba::Quaternion_copy (_tao_to, _tao_from);
}

ACE_INLINE
jpl::mipl::spice::corba::Quaternion_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::Quaternion,
    jpl::mipl::spice::corba::Quaternion_slice,
    jpl::mipl::spice::corba::Quaternion_tag
  >::alloc (void)
{
  return jpl::mipl::spice::corba::Quaternion_alloc ();
}


// TAO_IDL - Generated from
// be/be_visitor_array/array_ci.cpp:158

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::State,
    jpl::mipl::spice::corba::State_slice,
    jpl::mipl::spice::corba::State_tag
  >::free (
    jpl::mipl::spice::corba::State_slice * _tao_slice
  )
{
  jpl::mipl::spice::corba::State_free (_tao_slice);
}

ACE_INLINE
jpl::mipl::spice::corba::State_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::State,
    jpl::mipl::spice::corba::State_slice,
    jpl::mipl::spice::corba::State_tag
  >::dup (
    const jpl::mipl::spice::corba::State_slice * _tao_slice
  )
{
  return jpl::mipl::spice::corba::State_dup (_tao_slice);
}

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::State,
    jpl::mipl::spice::corba::State_slice,
    jpl::mipl::spice::corba::State_tag
  >::copy (
    jpl::mipl::spice::corba::State_slice * _tao_to,
    const jpl::mipl::spice::corba::State_slice * _tao_from
  )
{
  jpl::mipl::spice::corba::State_copy (_tao_to, _tao_from);
}

ACE_INLINE
jpl::mipl::spice::corba::State_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::State,
    jpl::mipl::spice::corba::State_slice,
    jpl::mipl::spice::corba::State_tag
  >::alloc (void)
{
  return jpl::mipl::spice::corba::State_alloc ();
}


// TAO_IDL - Generated from
// be/be_visitor_array/array_ci.cpp:158

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpEllipse::_center,
    jpl::mipl::spice::corba::SpEllipse::_center_slice,
    jpl::mipl::spice::corba::SpEllipse::_center_tag
  >::free (
    jpl::mipl::spice::corba::SpEllipse::_center_slice * _tao_slice
  )
{
  jpl::mipl::spice::corba::SpEllipse::_center_free (_tao_slice);
}

ACE_INLINE
jpl::mipl::spice::corba::SpEllipse::_center_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpEllipse::_center,
    jpl::mipl::spice::corba::SpEllipse::_center_slice,
    jpl::mipl::spice::corba::SpEllipse::_center_tag
  >::dup (
    const jpl::mipl::spice::corba::SpEllipse::_center_slice * _tao_slice
  )
{
  return jpl::mipl::spice::corba::SpEllipse::_center_dup (_tao_slice);
}

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpEllipse::_center,
    jpl::mipl::spice::corba::SpEllipse::_center_slice,
    jpl::mipl::spice::corba::SpEllipse::_center_tag
  >::copy (
    jpl::mipl::spice::corba::SpEllipse::_center_slice * _tao_to,
    const jpl::mipl::spice::corba::SpEllipse::_center_slice * _tao_from
  )
{
  jpl::mipl::spice::corba::SpEllipse::_center_copy (_tao_to, _tao_from);
}

ACE_INLINE
jpl::mipl::spice::corba::SpEllipse::_center_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpEllipse::_center,
    jpl::mipl::spice::corba::SpEllipse::_center_slice,
    jpl::mipl::spice::corba::SpEllipse::_center_tag
  >::alloc (void)
{
  return jpl::mipl::spice::corba::SpEllipse::_center_alloc ();
}


// TAO_IDL - Generated from
// be/be_visitor_array/array_ci.cpp:158

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpEllipse::_semiMajor,
    jpl::mipl::spice::corba::SpEllipse::_semiMajor_slice,
    jpl::mipl::spice::corba::SpEllipse::_semiMajor_tag
  >::free (
    jpl::mipl::spice::corba::SpEllipse::_semiMajor_slice * _tao_slice
  )
{
  jpl::mipl::spice::corba::SpEllipse::_semiMajor_free (_tao_slice);
}

ACE_INLINE
jpl::mipl::spice::corba::SpEllipse::_semiMajor_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpEllipse::_semiMajor,
    jpl::mipl::spice::corba::SpEllipse::_semiMajor_slice,
    jpl::mipl::spice::corba::SpEllipse::_semiMajor_tag
  >::dup (
    const jpl::mipl::spice::corba::SpEllipse::_semiMajor_slice * _tao_slice
  )
{
  return jpl::mipl::spice::corba::SpEllipse::_semiMajor_dup (_tao_slice);
}

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpEllipse::_semiMajor,
    jpl::mipl::spice::corba::SpEllipse::_semiMajor_slice,
    jpl::mipl::spice::corba::SpEllipse::_semiMajor_tag
  >::copy (
    jpl::mipl::spice::corba::SpEllipse::_semiMajor_slice * _tao_to,
    const jpl::mipl::spice::corba::SpEllipse::_semiMajor_slice * _tao_from
  )
{
  jpl::mipl::spice::corba::SpEllipse::_semiMajor_copy (_tao_to, _tao_from);
}

ACE_INLINE
jpl::mipl::spice::corba::SpEllipse::_semiMajor_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpEllipse::_semiMajor,
    jpl::mipl::spice::corba::SpEllipse::_semiMajor_slice,
    jpl::mipl::spice::corba::SpEllipse::_semiMajor_tag
  >::alloc (void)
{
  return jpl::mipl::spice::corba::SpEllipse::_semiMajor_alloc ();
}


// TAO_IDL - Generated from
// be/be_visitor_array/array_ci.cpp:158

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpEllipse::_semiMinor,
    jpl::mipl::spice::corba::SpEllipse::_semiMinor_slice,
    jpl::mipl::spice::corba::SpEllipse::_semiMinor_tag
  >::free (
    jpl::mipl::spice::corba::SpEllipse::_semiMinor_slice * _tao_slice
  )
{
  jpl::mipl::spice::corba::SpEllipse::_semiMinor_free (_tao_slice);
}

ACE_INLINE
jpl::mipl::spice::corba::SpEllipse::_semiMinor_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpEllipse::_semiMinor,
    jpl::mipl::spice::corba::SpEllipse::_semiMinor_slice,
    jpl::mipl::spice::corba::SpEllipse::_semiMinor_tag
  >::dup (
    const jpl::mipl::spice::corba::SpEllipse::_semiMinor_slice * _tao_slice
  )
{
  return jpl::mipl::spice::corba::SpEllipse::_semiMinor_dup (_tao_slice);
}

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpEllipse::_semiMinor,
    jpl::mipl::spice::corba::SpEllipse::_semiMinor_slice,
    jpl::mipl::spice::corba::SpEllipse::_semiMinor_tag
  >::copy (
    jpl::mipl::spice::corba::SpEllipse::_semiMinor_slice * _tao_to,
    const jpl::mipl::spice::corba::SpEllipse::_semiMinor_slice * _tao_from
  )
{
  jpl::mipl::spice::corba::SpEllipse::_semiMinor_copy (_tao_to, _tao_from);
}

ACE_INLINE
jpl::mipl::spice::corba::SpEllipse::_semiMinor_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpEllipse::_semiMinor,
    jpl::mipl::spice::corba::SpEllipse::_semiMinor_slice,
    jpl::mipl::spice::corba::SpEllipse::_semiMinor_tag
  >::alloc (void)
{
  return jpl::mipl::spice::corba::SpEllipse::_semiMinor_alloc ();
}


// TAO_IDL - Generated from
// be/be_visitor_array/array_ci.cpp:158

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpPlane::_normal,
    jpl::mipl::spice::corba::SpPlane::_normal_slice,
    jpl::mipl::spice::corba::SpPlane::_normal_tag
  >::free (
    jpl::mipl::spice::corba::SpPlane::_normal_slice * _tao_slice
  )
{
  jpl::mipl::spice::corba::SpPlane::_normal_free (_tao_slice);
}

ACE_INLINE
jpl::mipl::spice::corba::SpPlane::_normal_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpPlane::_normal,
    jpl::mipl::spice::corba::SpPlane::_normal_slice,
    jpl::mipl::spice::corba::SpPlane::_normal_tag
  >::dup (
    const jpl::mipl::spice::corba::SpPlane::_normal_slice * _tao_slice
  )
{
  return jpl::mipl::spice::corba::SpPlane::_normal_dup (_tao_slice);
}

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpPlane::_normal,
    jpl::mipl::spice::corba::SpPlane::_normal_slice,
    jpl::mipl::spice::corba::SpPlane::_normal_tag
  >::copy (
    jpl::mipl::spice::corba::SpPlane::_normal_slice * _tao_to,
    const jpl::mipl::spice::corba::SpPlane::_normal_slice * _tao_from
  )
{
  jpl::mipl::spice::corba::SpPlane::_normal_copy (_tao_to, _tao_from);
}

ACE_INLINE
jpl::mipl::spice::corba::SpPlane::_normal_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpPlane::_normal,
    jpl::mipl::spice::corba::SpPlane::_normal_slice,
    jpl::mipl::spice::corba::SpPlane::_normal_tag
  >::alloc (void)
{
  return jpl::mipl::spice::corba::SpPlane::_normal_alloc ();
}


// TAO_IDL - Generated from
// be/be_visitor_array/array_ci.cpp:158

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpDouble2,
    jpl::mipl::spice::corba::SpDouble2_slice,
    jpl::mipl::spice::corba::SpDouble2_tag
  >::free (
    jpl::mipl::spice::corba::SpDouble2_slice * _tao_slice
  )
{
  jpl::mipl::spice::corba::SpDouble2_free (_tao_slice);
}

ACE_INLINE
jpl::mipl::spice::corba::SpDouble2_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpDouble2,
    jpl::mipl::spice::corba::SpDouble2_slice,
    jpl::mipl::spice::corba::SpDouble2_tag
  >::dup (
    const jpl::mipl::spice::corba::SpDouble2_slice * _tao_slice
  )
{
  return jpl::mipl::spice::corba::SpDouble2_dup (_tao_slice);
}

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpDouble2,
    jpl::mipl::spice::corba::SpDouble2_slice,
    jpl::mipl::spice::corba::SpDouble2_tag
  >::copy (
    jpl::mipl::spice::corba::SpDouble2_slice * _tao_to,
    const jpl::mipl::spice::corba::SpDouble2_slice * _tao_from
  )
{
  jpl::mipl::spice::corba::SpDouble2_copy (_tao_to, _tao_from);
}

ACE_INLINE
jpl::mipl::spice::corba::SpDouble2_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpDouble2,
    jpl::mipl::spice::corba::SpDouble2_slice,
    jpl::mipl::spice::corba::SpDouble2_tag
  >::alloc (void)
{
  return jpl::mipl::spice::corba::SpDouble2_alloc ();
}


// TAO_IDL - Generated from
// be/be_visitor_array/array_ci.cpp:158

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpDouble6,
    jpl::mipl::spice::corba::SpDouble6_slice,
    jpl::mipl::spice::corba::SpDouble6_tag
  >::free (
    jpl::mipl::spice::corba::SpDouble6_slice * _tao_slice
  )
{
  jpl::mipl::spice::corba::SpDouble6_free (_tao_slice);
}

ACE_INLINE
jpl::mipl::spice::corba::SpDouble6_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpDouble6,
    jpl::mipl::spice::corba::SpDouble6_slice,
    jpl::mipl::spice::corba::SpDouble6_tag
  >::dup (
    const jpl::mipl::spice::corba::SpDouble6_slice * _tao_slice
  )
{
  return jpl::mipl::spice::corba::SpDouble6_dup (_tao_slice);
}

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpDouble6,
    jpl::mipl::spice::corba::SpDouble6_slice,
    jpl::mipl::spice::corba::SpDouble6_tag
  >::copy (
    jpl::mipl::spice::corba::SpDouble6_slice * _tao_to,
    const jpl::mipl::spice::corba::SpDouble6_slice * _tao_from
  )
{
  jpl::mipl::spice::corba::SpDouble6_copy (_tao_to, _tao_from);
}

ACE_INLINE
jpl::mipl::spice::corba::SpDouble6_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpDouble6,
    jpl::mipl::spice::corba::SpDouble6_slice,
    jpl::mipl::spice::corba::SpDouble6_tag
  >::alloc (void)
{
  return jpl::mipl::spice::corba::SpDouble6_alloc ();
}


// TAO_IDL - Generated from
// be/be_visitor_array/array_ci.cpp:158

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpDouble8,
    jpl::mipl::spice::corba::SpDouble8_slice,
    jpl::mipl::spice::corba::SpDouble8_tag
  >::free (
    jpl::mipl::spice::corba::SpDouble8_slice * _tao_slice
  )
{
  jpl::mipl::spice::corba::SpDouble8_free (_tao_slice);
}

ACE_INLINE
jpl::mipl::spice::corba::SpDouble8_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpDouble8,
    jpl::mipl::spice::corba::SpDouble8_slice,
    jpl::mipl::spice::corba::SpDouble8_tag
  >::dup (
    const jpl::mipl::spice::corba::SpDouble8_slice * _tao_slice
  )
{
  return jpl::mipl::spice::corba::SpDouble8_dup (_tao_slice);
}

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpDouble8,
    jpl::mipl::spice::corba::SpDouble8_slice,
    jpl::mipl::spice::corba::SpDouble8_tag
  >::copy (
    jpl::mipl::spice::corba::SpDouble8_slice * _tao_to,
    const jpl::mipl::spice::corba::SpDouble8_slice * _tao_from
  )
{
  jpl::mipl::spice::corba::SpDouble8_copy (_tao_to, _tao_from);
}

ACE_INLINE
jpl::mipl::spice::corba::SpDouble8_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpDouble8,
    jpl::mipl::spice::corba::SpDouble8_slice,
    jpl::mipl::spice::corba::SpDouble8_tag
  >::alloc (void)
{
  return jpl::mipl::spice::corba::SpDouble8_alloc ();
}


// TAO_IDL - Generated from
// be/be_visitor_array/array_ci.cpp:158

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpChar1,
    jpl::mipl::spice::corba::SpChar1_slice,
    jpl::mipl::spice::corba::SpChar1_tag
  >::free (
    jpl::mipl::spice::corba::SpChar1_slice * _tao_slice
  )
{
  jpl::mipl::spice::corba::SpChar1_free (_tao_slice);
}

ACE_INLINE
jpl::mipl::spice::corba::SpChar1_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpChar1,
    jpl::mipl::spice::corba::SpChar1_slice,
    jpl::mipl::spice::corba::SpChar1_tag
  >::dup (
    const jpl::mipl::spice::corba::SpChar1_slice * _tao_slice
  )
{
  return jpl::mipl::spice::corba::SpChar1_dup (_tao_slice);
}

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpChar1,
    jpl::mipl::spice::corba::SpChar1_slice,
    jpl::mipl::spice::corba::SpChar1_tag
  >::copy (
    jpl::mipl::spice::corba::SpChar1_slice * _tao_to,
    const jpl::mipl::spice::corba::SpChar1_slice * _tao_from
  )
{
  jpl::mipl::spice::corba::SpChar1_copy (_tao_to, _tao_from);
}

ACE_INLINE
jpl::mipl::spice::corba::SpChar1_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::SpChar1,
    jpl::mipl::spice::corba::SpChar1_slice,
    jpl::mipl::spice::corba::SpChar1_tag
  >::alloc (void)
{
  return jpl::mipl::spice::corba::SpChar1_alloc ();
}


// TAO_IDL - Generated from
// be/be_visitor_array/array_ci.cpp:158

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::Matrix66,
    jpl::mipl::spice::corba::Matrix66_slice,
    jpl::mipl::spice::corba::Matrix66_tag
  >::free (
    jpl::mipl::spice::corba::Matrix66_slice * _tao_slice
  )
{
  jpl::mipl::spice::corba::Matrix66_free (_tao_slice);
}

ACE_INLINE
jpl::mipl::spice::corba::Matrix66_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::Matrix66,
    jpl::mipl::spice::corba::Matrix66_slice,
    jpl::mipl::spice::corba::Matrix66_tag
  >::dup (
    const jpl::mipl::spice::corba::Matrix66_slice * _tao_slice
  )
{
  return jpl::mipl::spice::corba::Matrix66_dup (_tao_slice);
}

ACE_INLINE
void
TAO::Array_Traits<
    jpl::mipl::spice::corba::Matrix66,
    jpl::mipl::spice::corba::Matrix66_slice,
    jpl::mipl::spice::corba::Matrix66_tag
  >::copy (
    jpl::mipl::spice::corba::Matrix66_slice * _tao_to,
    const jpl::mipl::spice::corba::Matrix66_slice * _tao_from
  )
{
  jpl::mipl::spice::corba::Matrix66_copy (_tao_to, _tao_from);
}

ACE_INLINE
jpl::mipl::spice::corba::Matrix66_slice *
TAO::Array_Traits<
    jpl::mipl::spice::corba::Matrix66,
    jpl::mipl::spice::corba::Matrix66_slice,
    jpl::mipl::spice::corba::Matrix66_tag
  >::alloc (void)
{
  return jpl::mipl::spice::corba::Matrix66_alloc ();
}


// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ci.cpp:70

#if !defined (_JPL_MIPL_SPICE_CORBA_SPICELIB___CI_)
#define _JPL_MIPL_SPICE_CORBA_SPICELIB___CI_

ACE_INLINE
jpl::mipl::spice::corba::SpiceLib::SpiceLib (
    TAO_Stub *objref,
    ::CORBA::Boolean _tao_collocated,
    TAO_Abstract_ServantBase *servant,
    TAO_ORB_Core *oc
  )
  : ACE_NESTED_CLASS (CORBA, Object) (
        objref,
        _tao_collocated,
        servant,
        oc
      ),
    the_TAO_SpiceLib_Proxy_Broker_ (0)
{
  this->jpl_mipl_spice_corba_SpiceLib_setup_collocation ();
}

ACE_INLINE
jpl::mipl::spice::corba::SpiceLib::SpiceLib (
    IOP::IOR *ior,
    TAO_ORB_Core *oc
  )
  : ACE_NESTED_CLASS ( ::CORBA, Object) (ior, oc),
    the_TAO_SpiceLib_Proxy_Broker_ (0)
{
}

#endif /* end #if !defined */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ci.cpp:70

#if !defined (_JPL_MIPL_SPICE_CORBA_NAIFID___CI_)
#define _JPL_MIPL_SPICE_CORBA_NAIFID___CI_

ACE_INLINE
jpl::mipl::spice::corba::NaifId::NaifId (
    TAO_Stub *objref,
    ::CORBA::Boolean _tao_collocated,
    TAO_Abstract_ServantBase *servant,
    TAO_ORB_Core *oc
  )
  : ACE_NESTED_CLASS (CORBA, Object) (
        objref,
        _tao_collocated,
        servant,
        oc
      ),
    the_TAO_NaifId_Proxy_Broker_ (0)
{
  this->jpl_mipl_spice_corba_NaifId_setup_collocation ();
}

ACE_INLINE
jpl::mipl::spice::corba::NaifId::NaifId (
    IOP::IOR *ior,
    TAO_ORB_Core *oc
  )
  : ACE_NESTED_CLASS ( ::CORBA, Object) (ior, oc),
    the_TAO_NaifId_Proxy_Broker_ (0)
{
}

#endif /* end #if !defined */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ci.cpp:70

#if !defined (_JPL_MIPL_SPICE_CORBA_MIPLID___CI_)
#define _JPL_MIPL_SPICE_CORBA_MIPLID___CI_

ACE_INLINE
jpl::mipl::spice::corba::MiplId::MiplId (
    TAO_Stub *objref,
    ::CORBA::Boolean _tao_collocated,
    TAO_Abstract_ServantBase *servant,
    TAO_ORB_Core *oc
  )
  : ACE_NESTED_CLASS (CORBA, Object) (
        objref,
        _tao_collocated,
        servant,
        oc
      ),
    the_TAO_MiplId_Proxy_Broker_ (0)
{
  this->jpl_mipl_spice_corba_MiplId_setup_collocation ();
}

ACE_INLINE
jpl::mipl::spice::corba::MiplId::MiplId (
    IOP::IOR *ior,
    TAO_ORB_Core *oc
  )
  : ACE_NESTED_CLASS ( ::CORBA, Object) (ior, oc),
    the_TAO_MiplId_Proxy_Broker_ (0)
{
}

#endif /* end #if !defined */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ci.cpp:70

#if !defined (_JPL_MIPL_SPICE_CORBA_MIPLMISSIONNAME___CI_)
#define _JPL_MIPL_SPICE_CORBA_MIPLMISSIONNAME___CI_

ACE_INLINE
jpl::mipl::spice::corba::MiplMissionName::MiplMissionName (
    TAO_Stub *objref,
    ::CORBA::Boolean _tao_collocated,
    TAO_Abstract_ServantBase *servant,
    TAO_ORB_Core *oc
  )
  : ACE_NESTED_CLASS (CORBA, Object) (
        objref,
        _tao_collocated,
        servant,
        oc
      ),
    the_TAO_MiplMissionName_Proxy_Broker_ (0)
{
  this->jpl_mipl_spice_corba_MiplMissionName_setup_collocation ();
}

ACE_INLINE
jpl::mipl::spice::corba::MiplMissionName::MiplMissionName (
    IOP::IOR *ior,
    TAO_ORB_Core *oc
  )
  : ACE_NESTED_CLASS ( ::CORBA, Object) (ior, oc),
    the_TAO_MiplMissionName_Proxy_Broker_ (0)
{
}

#endif /* end #if !defined */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ci.cpp:70

#if !defined (_JPL_MIPL_SPICE_CORBA_MIPLSPICELIB___CI_)
#define _JPL_MIPL_SPICE_CORBA_MIPLSPICELIB___CI_

ACE_INLINE
jpl::mipl::spice::corba::MiplSpiceLib::MiplSpiceLib (
    TAO_Stub *objref,
    ::CORBA::Boolean _tao_collocated,
    TAO_Abstract_ServantBase *servant,
    TAO_ORB_Core *oc
  )
  : ACE_NESTED_CLASS (CORBA, Object) (
        objref,
        _tao_collocated,
        servant,
        oc
      ),
    the_TAO_MiplSpiceLib_Proxy_Broker_ (0)
{
  this->jpl_mipl_spice_corba_MiplSpiceLib_setup_collocation ();
}

ACE_INLINE
jpl::mipl::spice::corba::MiplSpiceLib::MiplSpiceLib (
    IOP::IOR *ior,
    TAO_ORB_Core *oc
  )
  : ACE_NESTED_CLASS ( ::CORBA, Object) (ior, oc),
    the_TAO_MiplSpiceLib_Proxy_Broker_ (0)
{
}

#endif /* end #if !defined */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ci.cpp:70

#if !defined (_JPL_MIPL_SPICE_CORBA_SPICELIBFACTORY___CI_)
#define _JPL_MIPL_SPICE_CORBA_SPICELIBFACTORY___CI_

ACE_INLINE
jpl::mipl::spice::corba::SpiceLibFactory::SpiceLibFactory (
    TAO_Stub *objref,
    ::CORBA::Boolean _tao_collocated,
    TAO_Abstract_ServantBase *servant,
    TAO_ORB_Core *oc
  )
  : ACE_NESTED_CLASS (CORBA, Object) (
        objref,
        _tao_collocated,
        servant,
        oc
      ),
    the_TAO_SpiceLibFactory_Proxy_Broker_ (0)
{
  this->jpl_mipl_spice_corba_SpiceLibFactory_setup_collocation ();
}

ACE_INLINE
jpl::mipl::spice::corba::SpiceLibFactory::SpiceLibFactory (
    IOP::IOR *ior,
    TAO_ORB_Core *oc
  )
  : ACE_NESTED_CLASS ( ::CORBA, Object) (ior, oc),
    the_TAO_SpiceLibFactory_Proxy_Broker_ (0)
{
}

#endif /* end #if !defined */

